behaviors:
  Foosbots_MultiRod_5:
    trainer_type: sac
    hyperparameters:
      batch_size: 1024
      buffer_size: 1000000
      learning_rate: 0.0002       #0.0002
      learning_rate_schedule: constant
      buffer_init_steps: 7500
      steps_per_update: 128
      init_entcoef: 1.0
      save_replay_buffer: true
      tau: 0.005
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3  #increase?
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.0001
        gamma: 0.99
        network_settings:
          normalize: true
          hidden_units: 64
          learning_rate: 0.0003
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 10000
    # self_play:
    #     window: 10
    #     play_against_latest_model_ratio: 0.5
    #     save_steps: 50000
    #     swap_steps: 50000
    #     team_change: 100000